name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-push:
    name: Build Docker Image and push it to registry
    runs-on: ubuntu-latest

    env: 
      DOCKER_BUILDKIT: 1 
      IMAGE_NAME: ipmi-api-gateway

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login and setup
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PAT}}
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag ${{secrets.DOCKER_USER}}/$IMAGE_NAME:latest
    - name: Push the Docker image
      run: docker push ${{secrets.DOCKER_USER}}/$IMAGE_NAME:latest
